text_ = input("Please Enter String To Convert it to Upper Case or To Lower Case:")
print("Your Entered String Is: ", text_)
str_upper = text_.upper()
print("Converted Uppercase String Is: ", str_upper)
str_lower = text_.lower()
print("Converted Lowercase String Is: ", str_lower)
str_capitalize = text_.capitalize()
print("Converted Capitalize(First Letter Uppercase) String Is: ", str_capitalize)
print("Immutable(unmodifiable) string(feature)?: text_ = ", text_)
